// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Maja Bojarska",
            "url": "https://github.com/majabojarska/fibo",
            "email": "majabojarska98@gmail.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://github.com/majabojarska/fibo?tab=MIT-1-ov-file#readme"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fibonacci/{count}": {
            "get": {
                "description": "Generates a finite length Fibonacci sequence",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fibonacci"
                ],
                "summary": "Get Fibonacci sequence",
                "operationId": "get-fibonacci",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "name": "count",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Fibonacci sequence items",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/livez": {
            "get": {
                "tags": [
                    "healthcheck"
                ],
                "summary": "Get liveness",
                "operationId": "get-livez",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "tags": [
                    "healthcheck"
                ],
                "summary": "Get readiness",
                "operationId": "get-readyz",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Fibo",
	Description:      "Fibonacci sequence REST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
