basePath: /
host: localhost:8080
info:
  contact:
    email: majabojarska98@gmail.com
    name: Maja Bojarska
    url: https://github.com/majabojarska/fibo
  description: Fibonacci sequence REST API
  license:
    name: MIT License
    url: https://github.com/majabojarska/fibo?tab=MIT-1-ov-file#readme
  title: Fibo
  version: "1.0"
paths:
  /api/v1/fibonacci/{count}/stream:
    get:
      description: Generates a finite length Fibonacci sequence
      operationId: get-fibonacci
      parameters:
      - in: path
        minimum: 0
        name: count
        type: integer
      produces:
      - text/event-stream
      responses:
        "400":
          description: Bad request
          schema:
            type: string
        "415":
          description: Unsupported media type
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get Fibonacci sequence
      tags:
      - fibonacci
  /livez:
    get:
      operationId: get-livez
      responses:
        "200":
          description: OK
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get liveness
      tags:
      - healthcheck
  /readyz:
    get:
      operationId: get-readyz
      responses:
        "200":
          description: OK
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get readiness
      tags:
      - healthcheck
swagger: "2.0"
