name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    name: Swag docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Swag init
        run: swag init --dir ./cmd/api

  docker:
    name: Docker build and compose up
    runs-on: ubuntu-latest
    env:
      PATH_COMPOSE_FILE: "./docker-compose.yaml"
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Compose build
        run: docker compose --file "${PATH_COMPOSE_FILE}" build

      - name: Compose up
        run: docker compose --file "${PATH_COMPOSE_FILE}" up -d --wait
