name: Lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1

  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # History is required by gitleaks
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  swag:
    name: Swag fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Assert 'swag fmt' made no diff
        run: |
          if [[ `git status --porcelain` ]]; then
            git diff
            echo "Swag fmt generated a diff. Run 'swag fmt' locally to correct swag annotation formatting."
            exit 1
          else
            echo "Swag fmt made no changes"
          fi
